### PR TITLE
Adding an nginx container as ingress

### PR DESCRIPTION
**Pull request by maoo**
Translate ports to paths to avoid CORS limits

### CODE REVIEW

**Comment by maoo** [comment]
Ok, I've pulled this branch from our EC2 instance, and apparently now https://traderx.finos.org works better, but there are still errors appearing on console:

```
WebSocket connection to 'wss://traderx.finos.org/ng-cli-ws' failed

GET https://traderx.finos.org/socket.io/?EIO=4&transport=polling&t=Os3OJP6 404 (Not Found)
```

Also, the changes on the following files break the local run of docker compose:
- web-front-end/angular/main/environments/environment.prod.ts
- web-front-end/angular/main/environments/environment.ts

We need to run `npm run build` and `npm run build-prod` depending on the environment, but I could not find where the build script is invoked for `web-front-end/angular`.

**Comment by DovOps** [comment]
FYI - I've been playing wiht this branch, to try and get the necessary options enabled for socket.io/* and websockets in general. There's a websocket for the webpack server running inside angular-cli driven front-end, for refreshing live changes, and that's currently blocked, and then there's the /socket.io/* which sources both regular HTTP traffic (and JS static files) as well as the websocket, off of the trade-feed. Both need accomodating in the nginx conf, and I'm playing with some configurations there, which still aren't 100% ready.

**Comment by rocketstack-matt** [comment]
I've started looking at this, but have been unable to far to get this all run up on a single host with everything communicating. Not sure if there is something wrong in my env or the changes.

**Comment by DovOps** [comment]
> I've started looking at this, but have been unable to far to get this all run up on a single host with everything communicating. Not sure if there is something wrong in my env or the changes.

Have you tried this in codespaces or just locally? Where do things break down for you?

**Comment by DovOps** [comment]
working locally, I see some bad assumptions in the web front end now... Those are being fixed:

1) window.location.hostname needs to be 'window.location.host' in order to include ports, when specified
2) 'https://' prefix in the angular environment.*.ts files needs to just be '//' to account for when local testing is done over http....

Will get those changes in.

**Comment by rocketstack-matt** [comment]
Sorry I didn't get a chance to reply - I was having issues with both, which I guess with what you've seen makes sense.

**Comment by DovOps** [comment]
@rocketstack-matt  once https://github.com/finos/traderX/pull/115 is merged in, this should address your issue

**Comment by rocketstack-matt** [comment]
I've just pulled it and testing, will let you know

**Review by rocketstack-matt — APPROVED** [review]
This looks goof with #115 merged . . . tested locally on M1 Mac and in Codespaces and both work.

**Comment by maoo** [comment]
Ok, I think that now https://traderx.finos.org is fully functional; @DovOps @rocketstack-matt - could you please have a look?

I had to add the `proxy_header` configuration for `ng-cli-ws`, `trade-feed` and `socket.io`; I've updated the deployment instructions on https://gist.github.com/maoo/51aef572973456437e28748200149126

**Comment by rocketstack-matt** [comment]
Looking good to me

**Comment by maoo** [comment]
Awesome - @DovOps , if you're ok with it, feel free to hit the Merge (and squash please, my commit history is terrible) button.

**Pull request merged**
