### PR TITLE
Refactor/update gradle wrapper

### PR DESCRIPTION
**Pull request by DovOps**
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS Corporate Contributor License Agreement.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by DovOps** [comment]
@maoo  this is ready to upgrade now.

**Comment by DovOps** [comment]
@maoo  let me know about this one, as I think the other spring upgrade may have broken docker builds due to some missed changes to base image

**Comment by maoo** [comment]
@DovOps - we run the upgrade as documented on https://gist.github.com/maoo/51aef572973456437e28748200149126

We're getting a rather cryptic error:

```
9.359 Welcome to Gradle 8.6!
9.359 
9.360 Here are the highlights of this release:
9.360  - Configurable encryption key for configuration cache
9.360  - Build init improvements
9.360  - Build authoring improvements
9.360 
9.360 For more details see https://docs.gradle.org/8.6/release-notes.html
9.361 
9.753 Starting a Gradle Daemon (subsequent builds will be faster)
74.06 > Task :compileJava FAILED
74.16 
74.16 FAILURE: 
74.16 Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
74.16 
74.16 You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
```

It seems that Gradle Forum responses don't help much either - https://discuss.gradle.org/t/deprecated-gradle-features-were-used-in-this-build-making-it-incompatible-with-gradle-9-0/48195

With OSFF tomorrow, we don't have bandwidth to debug this, but right now https://demo.traderx.finos.org is down.

I'll try to revert to the previous version for now, but would be great if someone can investigate what is going on.

**Comment by maoo** [comment]
> @maoo let me know about this one, as I think the other spring upgrade may have broken docker builds due to some missed changes to base image

Looks like we typed at the same time 😄 .

Is there any step of the deployment process that needs adapting?

**Comment by DovOps** [comment]
@maoo  merge this - it fixes this

**Comment by DovOps** [comment]
@maoo  this is fixed per https://github.com/DovOps/traderX/actions/runs/9661172553

**Comment by maoo** [comment]
> @maoo merge this - it fixes this

🤦 of course.

We're back and up to date - https://demo.traderx.finos.org

**Pull request merged**
