### PR TITLE
Fix People Service, and make Account-User UX more inutitive

### LINKED ISSUE #130: Add User to Account appears to be broken
### Steps to Reproduce:
Go to accounts tab.  
Select account.
Enter user not found in account
Click 'Add User'

### Expected Result:
Expect to see user added to account

### Actual Result:
User not added to account

### Environment:
...version and build of the project, OS and runtime versions, virtualised environment (if any), etc. ...

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

### PR DESCRIPTION
**Pull request by DovOps**
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS Corporate Contributor License Agreement.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

============================================
This fixes #130 

- Fixes some buggy routing logic around people service/gui relationship
- Fixes a bug in .NET people service with response format
- Makes the add-user-to-account flow more intuitive

### CODE REVIEW

**Comment by DovOps** [comment]
@maoo  can you please take a look at the netlify failures? Seems more config/environmental than related to the code, and this bot appears to be a new addition.

@fhubi  - I believe you need to make your profile public and re-run EasyCLA check, and/or click the link above within the failed step.

**Comment by maoo** [comment]
`Base directory does not exist: /opt/build/repo/website`

I suppose that this branch still doesn't include the docusaurus code, however the netflify github app is already running.

**Comment by DovOps** [comment]
Thanks. That makes sense. I couldn't find the configuration to see how it applied on this branch. I will ignore those errors on this branch. As soon as the CLA matter is sorted, this can be merged, if you are happy with the code changed otherwise. I tested changed locally and via nginx ingress docker-compose.

**Comment by psmulovics** [comment]
@maoo, CLA side fixed, feel free to merge

**Comment by fhubi** [comment]
@DovOps It worked. The PR looks good to me.

**Pull request merged**
