### PR TITLE
Fixed CI job (now green)

### PR DESCRIPTION
**Pull request by DovOps**
Confirmed this works in my local fork 
https://github.com/DovOps/traderX/actions/runs/10991091886

#
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS Corporate Contributor License Agreement.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by DovOps** [comment]
@maoo  this one works. Please check and merge

**Comment by willtsai** [comment]
@DovOps and @maoo - thank you for fixing this! Can you please help out with one more thing: the published images aren't showing up for me and I'm suspecting that they are set to `private` by default. Can one of you please help with changing all the traderX images to `public`?

**Comment by maoo** [comment]
> @DovOps and @maoo - thank you for fixing this! Can you please help out with one more thing: the published images aren't showing up for me and I'm suspecting that they are set to `private` by default. Can one of you please help with changing all the traderX images to `public`?

Done! Please let me know if it's all good now.

Would be possible to also add a scanning step? Maybe https://github.com/marketplace/actions/container-scan could come in handy. TY!

**Comment by willtsai** [comment]
> > @DovOps and @maoo - thank you for fixing this! Can you please help out with one more thing: the published images aren't showing up for me and I'm suspecting that they are set to `private` by default. Can one of you please help with changing all the traderX images to `public`?
> 
> Done! Please let me know if it's all good now.
> 
> Would be possible to also add a scanning step? Maybe https://github.com/marketplace/actions/container-scan could come in handy. TY!

Confirmed that it works now, thanks! I will take a look at adding a scanning step and send a PR for that.

**Pull request merged**
