### PR TITLE
Add github action for continuous integration

### PR DESCRIPTION
**Pull request by willtsai**
Per the comment in https://github.com/finos/traderX/pull/204#discussion_r1766598252, I am contributing a GitHub Action to bring continuous integration for the TraderX docker images.

### CODE REVIEW

**Comment by willtsai** [comment]
@maoo -- please give this a review, thanks!

**Comment by maoo** [comment]
> @maoo -- please give this a review, thanks!

Spotless 😄 

@DovOps - FYI, this github action is supposed - for now - to be manually executed by a TraderX maintainer; could you please review/merge this PR and then run the action? Please let @willtsai know the outcome. Thanks!

**Comment by DovOps** [comment]
@maoo  @willtsai  - I reviewed and merged this change (Thanks for putting this in!) - Action is running now.

**Comment by DovOps** [comment]
The action failed. I didn't catch this - but traderX is case sensitive, and in your paths it's not referenced properly.  This needs fixing.

**Pull request merged**
