### PR TITLE
refactor: CVE Remediations

### PR DESCRIPTION
**Pull request by DovOps**
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_3?organizationId=ZWRmYWQ5MjgtNDJmZS00YTU3LThlYmUtMTVjOWIyZTcyZTlk

### CODE REVIEW

**Comment by DovOps** [comment]
#
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE APACHE LICENSE V.2.0. YOU MAY OBTAIN A COPY OF THE LICENSE AT https://www.apache.org/licenses/LICENSE-2.0. 

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

**Comment by DovOps** [comment]
@maoo  this fixes all CVE issues to date, bringing the project back to a green CVE scan.  Had to ignore one from express 5.0.1 (latest 'fixed' version) which had a CVE with CVSS 5.03 - slightly over the 5.0 threshold. Please approve/merge at your leisure.

**Review by maoo — APPROVED** [review]
LGTM!

**Comment by maoo** [comment]
@DovOps - merged, thanks! Feel free to ping @TheJuanAndOnly99 moving forward; I'll be supporting him when needed.

We should have automatic redeployments on https://demo.traderx.finos.org/ , right ? Is there any way to verify if the change have been redeployed (without accessing to EC2) ?

**Pull request merged**
